name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Java 21
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # ✅ FIX QUAN TRỌNG: cd vào demo
      - name: Build Maven
        run: |
          cd demo
          mvn clean package -DskipTests

      - name: Run Test
        run: |
          cd demo
          mvn test

      - name: Docker build
        run: |
          cd demo
          docker build -t demo-app .

  deploy-staging:
    needs: build-test-docker
    runs-on: ubuntu-latest

    steps:
      - run: echo "Deploy staging..."

  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest

    environment:
      name: production

    steps:
      - run: echo "Deploy production..."